name: keep alive

on:
  schedule:
  - cron:  '*/9 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_URL: https://nginx-uwsgi-flask.herokuapp.com/

    steps:
    - uses: actions/checkout@v2

    - name: ping application
      run: curl ${{ env.HEROKU_APP_URL }}