name: Schedule job - ping the application each 29 min

on:
  schedule:
    - cron:  '*/29 * * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      HEROKU_REGISTRY: registry.heroku.com
      HEROKU_APP_NAME: generate-tiny-url

    steps:
      - uses: actions/checkout@v2

      - name: Build backend image
        run: |
          curl ${{ env.HEROKU_REGISTRY }}/${{ env.HEROKU_APP_NAME }}